<a href="https://colab.research.google.com/github/Thiyophin/Computer_Vision/blob/master/Tensorflow_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,4.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  4.], shape=(4,), dtype=float32)


In [ ]:
tenosor_two_d = tf.constant([
    [1,2,0],
    [3,2,-1],
    [1,5,6],
    [12,32,6]
])
print(tenosor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  2 -1]
 [ 1  5  6]
 [12 32  6]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
 [[1,2,0],
[3,21,3]] ,

[[23,432,4323],
[323,435,325]],

[[12,654,8676],
[432,324,553]]
])
print(tensor_three_d)

tf.Tensor(
[[[   1    2    0]
  [   3   21    3]]

 [[  23  432 4323]
  [ 323  435  325]]

 [[  12  654 8676]
  [ 432  324  553]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
print(tensor_three_d.shape)

(3, 2, 3)


In [ ]:
print(tensor_three_d.ndim) # number of dimensions

3


In [ ]:
tensor_four_d = tf.constant([
[[[1,2,0],
[3,21,3]] ,
[[23,432,4323],
[323,435,325]],
[[12,654,8676],
[432,324,553]]],

[[[1,2,0],
[3,21,3]] ,
[[23,432,4323],
[323,435,325]],
[[12,654,8676],
[432,324,553]]],
])

In [ ]:
print(tensor_four_d.ndim)

4


In [ ]:
print(tensor_four_d.shape)

(2, 3, 2, 3)


In [ ]:
tensor_one_d = tf.constant([2,0,-3,8,90],dtype=tf.float32)
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [ ]:
tensor_one_d = tf.constant([2,0,-3.4,8,90],dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.   0.  -3.4  8.  90. ], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [ ]:
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool)
print(casted_tensor_one_d)

tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [ ]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
tensor_string = tf.constant(["hello world","hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [ ]:
import numpy as np
np_array = np.array([1,3,2])
print(np_array)

[1 3 2]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 3 2], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)

In [ ]:
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [ ]:
print(3*eye_tensor)

tf.Tensor(
[[[3. 0. 0.]
  [0. 3. 0.]
  [0. 0. 3.]]

 [[3. 0. 0.]
  [0. 3. 0.]
  [0. 0. 3.]]], shape=(2, 3, 3), dtype=float32)


In [ ]:
fill_tensor = tf.fill(
    [3,4],5
,name=None)

In [ ]:
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 10.0,
    stddev = 1.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)

In [ ]:
print(random_tensor)

tf.Tensor(
[[ 9.501034  10.317219 ]
 [ 9.3732195  9.715078 ]
 [ 9.281423  10.188942 ]], shape=(3, 2), dtype=float32)
